### ISSUE TITLE
[CI/CD] Setup Github Actions to automatically run unittest with each commit

### ISSUE THREAD

**Issue by johnwangwyx** [johnwangwyx/cmdCompass#2]
Unittests are currently in `./test` directory and can be run by:

`python -m unittest discover -s "./test" -t "./"`
(i.e running tests in `./test` from project's root)

We can setup a single GitHub Action to run the tests on Mac, Windows, and Linux (The three supported OS) with `runs-on: ${{ matrix.os }}`.

**Comment by DCRepublic** [comment]
Hi! Is this issue still open? If so, id love to contribute!

**Comment by DCRepublic** [comment]
If so, here is my pr. 

https://github.com/johnwangwyx/cmdCompass/pull/5

**Comment by johnwangwyx** [comment]
> Hi! Is this issue still open? If so, id love to contribute!

Thank you so much for looking into this issue! I have merged your PR. 
I am actually planning to do another release sometime this or next month so it will ease the release process. 

Thanks,
John

**Comment by DCRepublic** [comment]
Happy to help! 

If there is anything else I could help with in this area please let me know! I am actually currently taking a class about FOSS and the importance of contributions, and part of my assignments are to make pull requests to different repos/issues! So if you had any other issues to address I'd be happy to work on them.
